import { zodResolver } from '@hookform/resolvers/zod'
import { useMutation } from '@tanstack/react-query'
import { Eye, EyeOff } from 'lucide-react'
import { useState } from 'react'
import { useForm } from 'react-hook-form'
import { Link, useNavigate } from 'react-router-dom'
import { z } from 'zod'
import { authService, type RegisterRequest } from './auth-service'
import { AuthShell, Field } from './login-page'
import './auth-pages.css'

const passwordRule = /^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[@#$%^&+=!]).{8,20}$/
const schema = z.object({ firstName: z.string().min(1, 'First name is required').max(50), lastName: z.string().min(1, 'Last name is required').max(50), dateOfBirth: z.string().optional(), gender: z.enum(['MALE', 'FEMALE', 'OTHER']), phoneNumber: z.string().regex(/^\d{10}$/, 'Use exactly 10 digits'), email: z.string().email('Enter a valid email').max(100), username: z.string().regex(/^[A-Za-z0-9._]{4,20}$/, 'Use 4-20 letters, numbers, dots, or underscores'), password: z.string().regex(passwordRule, 'Use 8-20 characters with upper, lower, number, and special character'), confirmPassword: z.string().min(1, 'Confirm your password'), addressLine1: z.string().max(150).optional(), addressLine2: z.string().max(150).optional(), city: z.string().max(50).optional(), state: z.string().max(50).optional(), country: z.string().max(50).optional(), postalCode: z.string().max(15).optional() }).refine((data) => data.password === data.confirmPassword, { path: ['confirmPassword'], message: 'Passwords must match' })

export function RegisterPage() {
  const navigate = useNavigate(); const [showPassword, setShowPassword] = useState(false)
  const form = useForm<RegisterRequest>({ resolver: zodResolver(schema), defaultValues: { firstName: '', lastName: '', gender: 'OTHER', phoneNumber: '', email: '', username: '', password: '', confirmPassword: '' } })
  const mutation = useMutation({ mutationFn: authService.register, onSuccess: () => navigate('/login', { state: { registered: true } }) })
  return <AuthShell title="Create your account" subtitle="Start managing your policies in one secure place."><form onSubmit={form.handleSubmit((data) => mutation.mutate(data))} noValidate>{mutation.isError && <div className="auth-alert error">{mutation.error instanceof Error ? mutation.error.message : 'We could not create your account.'}</div>}<h3>Personal details</h3><div className="form-grid"><Field label="First name" error={form.formState.errors.firstName?.message}><input {...form.register('firstName')} /></Field><Field label="Last name" error={form.formState.errors.lastName?.message}><input {...form.register('lastName')} /></Field><Field label="Date of birth" error={form.formState.errors.dateOfBirth?.message}><input type="date" {...form.register('dateOfBirth')} /></Field><Field label="Gender" error={form.formState.errors.gender?.message}><select {...form.register('gender')}><option value="OTHER">Prefer not to say</option><option value="MALE">Male</option><option value="FEMALE">Female</option></select></Field></div><Field label="Phone number" error={form.formState.errors.phoneNumber?.message}><input inputMode="numeric" {...form.register('phoneNumber')} placeholder="10-digit number" /></Field><h3>Account details</h3><Field label="Email address" error={form.formState.errors.email?.message}><input type="email" autoComplete="email" {...form.register('email')} /></Field><Field label="Username" error={form.formState.errors.username?.message}><input autoComplete="username" {...form.register('username')} /></Field><div className="form-grid"><Field label="Password" error={form.formState.errors.password?.message}><span className="password-input"><input type={showPassword ? 'text' : 'password'} autoComplete="new-password" {...form.register('password')} /><button type="button" onClick={() => setShowPassword(!showPassword)}>{showPassword ? <EyeOff size={18} /> : <Eye size={18} />}</button></span></Field><Field label="Confirm password" error={form.formState.errors.confirmPassword?.message}><input type={showPassword ? 'text' : 'password'} autoComplete="new-password" {...form.register('confirmPassword')} /></Field></div><details><summary>Address details (optional)</summary><div className="form-grid address-grid"><Field label="Address line 1"><input {...form.register('addressLine1')} /></Field><Field label="Address line 2"><input {...form.register('addressLine2')} /></Field><Field label="City"><input {...form.register('city')} /></Field><Field label="State"><input {...form.register('state')} /></Field><Field label="Country"><input {...form.register('country')} /></Field><Field label="Postal code"><input {...form.register('postalCode')} /></Field></div></details><button className="auth-submit" disabled={mutation.isPending} type="submit">{mutation.isPending ? 'Creating account...' : 'Create secure account'}</button></form><p className="auth-switch">Already have an account? <Link to="/login">Sign in</Link></p></AuthShell>
}