import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ChevronLeft, ShieldCheck } from 'lucide-react'
import { Link } from 'react-router-dom'
import { apiClient, type ApiResponse } from '../../api/client'
import './policy-workspace.css'

type Policy = { id: number; policyNumber: string; customerUsername: string; productName: string; status: string; updatedAt?: string }
type Page<T> = { content: T[]; totalPages: number }
async function unwrap<T>(request: Promise<{ data: ApiResponse<T> }>) { const response = await request; if (!response.data.success) throw new Error(response.data.message); return response.data.data }
const api = { pending: () => unwrap(apiClient.get<ApiResponse<Page<Policy>>>('/api/policies/pending-cancellations', { params: { page: 0, size: 20 } })), approve: (id: number) => unwrap(apiClient.patch<ApiResponse<Policy>>(`/api/policies/${id}/approve-cancellation`)) }
export function CancellationPage() { const cache = useQueryClient(); const policies = useQuery({ queryKey: ['policies', 'pending-cancellations'], queryFn: api.pending }); const approve = useMutation({ mutationFn: api.approve, onSuccess: () => cache.invalidateQueries({ queryKey: ['policies'] }) }); return <main className="policy-workspace"><header><Link to="/admin/policies"><ChevronLeft size={17} />Policies</Link><span><ShieldCheck size={18} />Cancellation management</span></header><section className="policy-title"><p>POLICY LIFECYCLE</p><h1>Pending cancellations</h1></section>{policies.isLoading ? <div className="policy-state">Loading cancellation requests...</div> : policies.isError ? <div className="policy-state error">Unable to load cancellation requests.</div> : <section className="policy-table"><table><thead><tr><th>Policy number</th><th>Customer</th><th>Product</th><th>Request date</th><th>Status</th><th /></tr></thead><tbody>{policies.data?.content.map((policy) => <tr key={policy.id}><td><b>{policy.policyNumber}</b></td><td>{policy.customerUsername}</td><td>{policy.productName}</td><td>{policy.updatedAt ?? 'Not provided'}</td><td><span className="policy-status cancel_requested">{policy.status}</span></td><td><button className="policy-primary" disabled={approve.isPending} onClick={() => { if (window.confirm(`Approve cancellation for ${policy.policyNumber}?`)) approve.mutate(policy.id) }}>Approve</button></td></tr>)}</tbody></table></section>}{approve.isError && <p className="form-error">{approve.error.message}</p>}<p className="unavailable">Cancellation rejection is unavailable because the backend does not expose a rejection endpoint.</p></main> }