-- Initial schema bootstrap for clean PostgreSQL environments.
-- This migration creates the foundational tables expected by V3-V8.

CREATE TABLE IF NOT EXISTS customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    date_of_birth DATE NOT NULL,
    gender VARCHAR(30) NOT NULL,
    phone_number VARCHAR(15) NOT NULL,
    email VARCHAR(100) NOT NULL,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(30) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    address_line1 VARCHAR(150),
    address_line2 VARCHAR(150),
    city VARCHAR(50),
    state VARCHAR(50),
    country VARCHAR(50),
    postal_code VARCHAR(15)
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uk_customer_username') THEN
        ALTER TABLE customers ADD CONSTRAINT uk_customer_username UNIQUE (username);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uk_customer_email') THEN
        ALTER TABLE customers ADD CONSTRAINT uk_customer_email UNIQUE (email);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    product_name VARCHAR(100) NOT NULL,
    product_category VARCHAR(30) NOT NULL,
    coverage_amount NUMERIC(15, 2) NOT NULL,
    premium_amount NUMERIC(15, 2) NOT NULL,
    policy_tenure_months INTEGER NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    policy_number VARCHAR(40) NOT NULL,
    customer_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    nominee_name VARCHAR(100) NOT NULL,
    nominee_relation VARCHAR(60) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    renewal_premium NUMERIC(15, 2) NOT NULL,
    status VARCHAR(30) NOT NULL
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uk_policies_policy_number') THEN
        ALTER TABLE policies ADD CONSTRAINT uk_policies_policy_number UNIQUE (policy_number);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_policies_customer') THEN
        ALTER TABLE policies
            ADD CONSTRAINT fk_policies_customer
            FOREIGN KEY (customer_id) REFERENCES customers(id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_policies_product') THEN
        ALTER TABLE policies
            ADD CONSTRAINT fk_policies_product
            FOREIGN KEY (product_id) REFERENCES products(id);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS claims (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    claim_number VARCHAR(40) NOT NULL,
    policy_id BIGINT NOT NULL,
    submitted_by_customer_id BIGINT NOT NULL,
    incident_date DATE NOT NULL,
    description VARCHAR(2000) NOT NULL,
    supporting_documents VARCHAR(500),
    decision_reason VARCHAR(500),
    status VARCHAR(30) NOT NULL
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uk_claims_claim_number') THEN
        ALTER TABLE claims ADD CONSTRAINT uk_claims_claim_number UNIQUE (claim_number);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_claims_policy') THEN
        ALTER TABLE claims
            ADD CONSTRAINT fk_claims_policy
            FOREIGN KEY (policy_id) REFERENCES policies(id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_claims_submitted_by_customer') THEN
        ALTER TABLE claims
            ADD CONSTRAINT fk_claims_submitted_by_customer
            FOREIGN KEY (submitted_by_customer_id) REFERENCES customers(id);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    payment_reference VARCHAR(40) NOT NULL,
    policy_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    amount NUMERIC(15, 2) NOT NULL,
    payment_date TIMESTAMP NOT NULL,
    status VARCHAR(30) NOT NULL,
    invoice_number VARCHAR(40) NOT NULL,
    receipt_number VARCHAR(40) NOT NULL
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uk_payments_payment_reference') THEN
        ALTER TABLE payments ADD CONSTRAINT uk_payments_payment_reference UNIQUE (payment_reference);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_payments_policy') THEN
        ALTER TABLE payments
            ADD CONSTRAINT fk_payments_policy
            FOREIGN KEY (policy_id) REFERENCES policies(id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_payments_customer') THEN
        ALTER TABLE payments
            ADD CONSTRAINT fk_payments_customer
            FOREIGN KEY (customer_id) REFERENCES customers(id);
    END IF;

    -- Legacy name intentionally kept; V8 removes this after V7 introduces the new check.
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'payments_status_check') THEN
        ALTER TABLE payments
            ADD CONSTRAINT payments_status_check
                CHECK (status IN ('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', 'REFUNDED'));
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_policies_customer_id ON policies(customer_id);
CREATE INDEX IF NOT EXISTS idx_policies_product_id ON policies(product_id);
CREATE INDEX IF NOT EXISTS idx_claims_policy_id ON claims(policy_id);
CREATE INDEX IF NOT EXISTS idx_claims_submitted_by_customer_id ON claims(submitted_by_customer_id);
CREATE INDEX IF NOT EXISTS idx_payments_customer_id ON payments(customer_id);
CREATE INDEX IF NOT EXISTS idx_payments_policy_id ON payments(policy_id);
CREATE INDEX IF NOT EXISTS idx_payments_payment_date ON payments(payment_date);

