CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255),
    role VARCHAR(50),
    action VARCHAR(80) NOT NULL,
    entity_type VARCHAR(80),
    entity_identifier VARCHAR(255),
    event_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    details VARCHAR(1000)
);

CREATE INDEX IF NOT EXISTS idx_audit_log_timestamp ON audit_log (event_timestamp);
CREATE INDEX IF NOT EXISTS idx_audit_log_action ON audit_log (action);
CREATE INDEX IF NOT EXISTS idx_audit_log_username ON audit_log (username);